FORECAST_RESOURCE_ARN_PREFIX_KEY = "ForecastResourceArnPrefixKey"
TTS_DATASET_NAME_KEY = "TtsDatasetName"
TTS_DATASET_ARN_KEY = "TtsDatasetArn"
RTS_DATASET_NAME_KEY = "RtsDatasetName"
RTS_DATASET_ARN_KEY = "RtsDatasetArn"
META_DATASET_NAME_KEY = "MetaDatasetName"
META_DATASET_ARN_KEY = "MetaDatasetArn"
DATASET_GROUP_NAME_KEY = "DatasetGroupName"
DATASET_GROUP_ARN_KEY = "DatasetGroupArn"
TTS_DATASET_IMPORT_JOB_NAME_KEY = "TtsDatasetImportJobName"
TTS_DATASET_IMPORT_JOB_ARN_KEY = "TtsDatasetImportJobArn"
RTS_DATASET_IMPORT_JOB_NAME_KEY = "RtsDatasetImportJobName"
RTS_DATASET_IMPORT_JOB_ARN_KEY = "RtsDatasetImportJobArn"
META_DATASET_IMPORT_JOB_NAME_KEY = "MetaDatasetImportJobName"
META_DATASET_IMPORT_JOB_ARN_KEY = "MetaDatasetImportJobArn"
PREDICTOR_NAME_KEY = "PredictorName"
PREDICTOR_ARN_KEY = "PredictorArn"
FORECAST_NAME_KEY = "ForecastName"
FORECAST_ARN_KEY = "ForecastArn"
FORECAST_EXPORT_JOB_NAME_KEY = "ForecastExportJobName"
FORECAST_EXPORT_JOB_ARN_KEY = "ForecastExportJobArn"
EXPLAINABILITY_EXPORT_JOB_NAME_KEY = "ExplainabilityExportJobName"
EXPLAINABILITY_EXPORT_JOB_ARN_KEY = "ExplainabilityExportJobArn"
DATA_FREQUENCY_KEY = "DataFrequency"

ARN_COMPONENT_SPLITTER = ":"
FORECAST_SERVICE_NAME = "forecast"
DATASET_NAME_PREFIX = "ds_"
DATASET_GROUP_NAME_PREFIX = "dsg_"
DATASET_IMPORT_JOB_NAME_PREFIX = "dsij_"
PREDICTOR_NAME_PREFIX = "p_"
FORECAST_NAME_PREFIX = "f_"
FORECAST_EXPORT_JOB_NAME_PREFIX = "fej_"
EXPLAINABILITY_EXPORT_JOB_NAME_PREFIX = "exp_"

RESOURCE_ACTIVE_STATUS = "ACTIVE"
RESOURCE_CREATION_FAILED_STATUS = "CREATE_FAILED"
RESOURCE_FAILED_STATUS = "FAILED"

DATE_FORMAT = 'yyyy-MM-dd'
DATETIME_FORMAT = 'yyyy-MM-dd HH:mm:ss'

RANDOM_SEED = 42
VERSIONS_USE_NEW_API = ["1.5.1"]
